# Generated by Django 5.1.4 on 2024-12-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('page', models.IntegerField(default=0, verbose_name='Страница')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
            ],
        ),
    ]
